### ISSUE TITLE
packages conflict

### ISSUE THREAD

**Issue by yuan777** [lchdl/annotation_free_wmh_seg#5]
in the 5th step "Download DeepWMH", after cd DeepWMH folder and execute _pip install -e ._, I got a wrong message which is shown in the fellowing picture
![捕获](https://github.com/lchdl/DeepWMH/assets/21097413/3a0425ed-77d4-4e8e-9f18-ffdfdf540507)
when i try execute _pip install scipy==1.10_, then I got the following wrong
![捕获](https://github.com/lchdl/DeepWMH/assets/21097413/aa202cc8-d59d-4ff4-a185-294203e6dba2)
so, would you mind to help me to solve this packages confliction problems?

**Comment by lchdl** [comment]
Hi @yuan777,
1. Did you install DeepWMH in a completely clean Python virtual environment? If not, **try reinstalling DeepWMH in a clean Python virtual environment** to avoid potential package version conflicts.
2. If the problem still occurs, try **removing all version requirements** in "DeepWMH/**setup.py**" (see below), and then pip install again.
![image](https://github.com/lchdl/DeepWMH/assets/18594210/a1655600-a041-49e5-8adc-dce9d5c12403)

**Comment by yuan777** [comment]
> Hi @yuan777,
> 
> 1. Did you install DeepWMH in a completely clean Python virtual environment? If not, **try reinstalling DeepWMH in a clean Python virtual environment** to avoid potential package version conflicts.
> 2. If the problem still occurs, try **removing all version requirements** in "DeepWMH/**setup.py**" (see below), and then pip install again.
>    ![image](https://private-user-images.githubusercontent.com/18594210/324857858-a1655600-a041-49e5-8adc-dce9d5c12403.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTM5MjMxMDMsIm5iZiI6MTcxMzkyMjgwMywicGF0aCI6Ii8xODU5NDIxMC8zMjQ4NTc4NTgtYTE2NTU2MDAtYTA0MS00OWU1LThhZGMtZGNlOWQ1YzEyNDAzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MjQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDI0VDAxNDAwM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTE3YTgwYjFlMGVhOTc2Yjc1ZjYyYzEwYjVmN2VhMzEwNDk4YmE5MzY3ZTUzNTRhNWU2ZTQ1YWJjNTJiMWQ5NTQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.kJQlM83BxVH8MWEGKQTa580oe00cb-5xcEhu-bvgB0g)
thanks for your quickly response, the environment is newly created, i fellow your recommend to remove all packages' version requirement, the problem has been solved.
