### ISSUE TITLE
[REQUEST]: Save the pre-processed brain image that is actually used for training and/or evaluation.

### ISSUE THREAD

**Issue by thtranos** [lchdl/annotation_free_wmh_seg#6]
Hello!

This is not an issue but rather a request for help!

I would like to modify or intervene the pipeline in the correct spot (somewhere inside predict.py probably !?) in order to be able to save a case's preproccessed brain.nii.gz without the lesions masks.

So pretty much the original .nii.gz with ROBEX and N4BIasFieldCorrection applied (If i'm not wrong, I am assuming these two processes are what you are using for the overall preproccessing)

Could you provide me with any insights of how I could achieve that?

The reason of this need is that I want to compute some statistics based on intensities and I want to remain consistent with your approach, instead of computing robex and n4BiasFieldCorrection from start. It seems like robex has some stochasticity too...

I sincerely apologize delving into your work after such a long time but since I have made questions in the past and observed your welcoming and willing spirit, I thought of giving it a try :)!

Thank you,

Theodore Tranos

**Comment by lchdl** [comment]
Hi @thtranos,
Actually, all the preprocessed images are cached in a folder named **001_Preprocessed_Images/** (you can ignore the "_0000" suffix in the filenames). This folder is located in the root output directory that you specified. You don't need to modify any code for this. :smiley:
* Additionally, please note that ROBEX introduces some randomness in its algorithm (controlled by a random seed), so even the same image may yield slightly different results across different runs. If you want the skull stripping results to be deterministic, please refer to this [link](https://www.nitrc.org/forum/message.php?msg_id=11063).

**Comment by thtranos** [comment]
> Hi @thtranos, Actually, all the preprocessed images are cached in a folder named **001_Preprocessed_Images/** (you can ignore the "_0000" suffix in the filenames). This folder is located in the root output directory that you specified. You don't need to modify any code for this. 😃
> 
> * Additionally, please note that ROBEX introduces some randomness in its algorithm (controlled by a random seed), so even the same image may yield slightly different results across different runs. If you want the skull stripping results to be deterministic, please refer to this [link](https://www.nitrc.org/forum/message.php?msg_id=11063).

Thanks for the reply. I was aware of this repository but they seem to not have been ROBEXed, those scans are the originals with applied N4BiasFieldCorrection right?

Also thanks for the link.

**Comment by lchdl** [comment]
:smiley: Hi @thtranos,
Neither the ROBEX nor ANTs toolkits are included in this repository because they are too complex to fully integrate into the automatic installation process. If you haven't installed ROBEX or ANTs, the images will simply be copied without any modifications, so they will be identical to the originals.
If you have only installed ANTs, the preprocessing stage will only apply N4BiasFieldCorrection to the original image.

**Comment by thtranos** [comment]
> 😃 Hi @thtranos, Neither the ROBEX nor ANTs toolkits are included in this repository because they are too complex to fully integrate into the automatic installation process. If you haven't installed ROBEX or ANTs, the images will simply be copied without any modifications, so they will be identical to the originals. If you have only installed ANTs, the preprocessing stage will only apply N4BiasFieldCorrection to the original image.

I have installed both ROBEX and ANTs, I also think I pass the integrity_checks. If they are installed on my system they are supposed to be applied on these images on the preprocessed folder?

**Comment by lchdl** [comment]
@thtranos Yes, they are supposed to be applied to those images.
